name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
        with:
          persist-credentials: false
      - uses: "DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb" # v3
      - uses: "DeterminateSystems/flakehub-push@060a48ced97e8a164f3b733455697e9f9310d39b" # main
        with:
          name: "LowkeyLab/nix"
          rolling: true
          visibility: "public"
          include-output-paths: true
