name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
        with:
          persist-credentials: false
      - uses: "DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11" # v3
      - uses: "DeterminateSystems/flakehub-push@f960928265d16ba43227dfd48812a8b1de17a441" # main
        with:
          name: "LowkeyLab/nix"
          rolling: true
          visibility: "public"
          include-output-paths: true
